on:
  workflow_dispatch:
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: test depreacted function found
        run: |
          deprecated=true
          if [[ deprecated ]]; then
            echo "::warning::Depreacted function found"
          fi
