name: Test Secret Key
on:
  workflow_dispatch:

jobs:
  test_get_secret_key:
    runs-on: ubuntu-latest
    steps:
      - name: get_secret_key
        run: 'echo "This Is My Secret Key : ${{ secrets.API_KEY_Muhmmed }}"'
